'use client'

import { useEffect } from 'react'
import { isAbortError } from '@/lib/errors/isAbortError'
import { ABORT_REASON } from '@/lib/abort-reason'

/**
 * Client-side component that globally suppresses abort errors generated by
 * fetch requests. Next.js/Turbopack will abort in-flight requests when a
 * component unmounts or during navigation; these typically surface as
 * "signal is aborted without reason" unhandled rejections in the console.
 *
 * Rendering this component near the root of the app ensures the listener is
 * installed once and prevents that noisy message in **every** page.
 * 
 * This guard handles:
 * - Standard AbortError from fetch requests
 * - Unhandled promise rejections from aborted fetches
 * - Error events from abort signals
 * - "Signal abort" errors from network operations
 */

declare global {
  interface Window {
    __MOOLABASE_FETCH_GUARD_INSTALLED__?: boolean
    __MOOLABASE_FETCH_GUARD_ORIGINAL_ABORT__?: typeof AbortController.prototype.abort
    __MOOLABASE_FETCH_GUARD_ORIGINAL_REPORT_ERROR__?: ((error: any) => void) | undefined
    __MOOLABASE_FETCH_GUARD_ORIGINAL_CONSOLE_ERROR__?: typeof console.error
    __MOOLABASE_FETCH_GUARD_ORIGINAL_CONSOLE_WARN__?: typeof console.warn
  }
}

function installFetchGuard() {
  if (typeof window === 'undefined') return
  if (window.__MOOLABASE_FETCH_GUARD_INSTALLED__) return
  window.__MOOLABASE_FETCH_GUARD_INSTALLED__ = true

  const handleUnhandledRejection = (event: PromiseRejectionEvent) => {
    if (isAbortError(event.reason)) {
      event.preventDefault()
    }
  }

  const handleError = (event: ErrorEvent) => {
    if (isAbortError(event.error || event.message)) {
      event.preventDefault()
    }
  }

  window.addEventListener('unhandledrejection', handleUnhandledRejection)
  window.addEventListener('error', handleError, true)

  // Install the abort normalization immediately (module load) so StrictMode / early aborts
  // don't produce "signal is aborted without reason" before effects run.
  const originalAbort = AbortController.prototype.abort
  window.__MOOLABASE_FETCH_GUARD_ORIGINAL_ABORT__ = originalAbort

  function patchedAbort(this: AbortController, reason?: any) {
    if (arguments.length === 0 || reason === undefined) {
      return originalAbort.call(this, ABORT_REASON as any)
    }
    return originalAbort.call(this, reason)
  }

  if (process.env.NODE_ENV !== 'production') {
    AbortController.prototype.abort = patchedAbort as any
  }

  const originalReportError = (window as any).reportError as ((error: any) => void) | undefined
  window.__MOOLABASE_FETCH_GUARD_ORIGINAL_REPORT_ERROR__ = originalReportError
  if (typeof originalReportError === 'function') {
    ;(window as any).reportError = (error: any) => {
      if (isAbortError(error)) return
      return originalReportError(error)
    }
  }

  const originalConsoleError = console.error
  const originalConsoleWarn = console.warn
  window.__MOOLABASE_FETCH_GUARD_ORIGINAL_CONSOLE_ERROR__ = originalConsoleError
  window.__MOOLABASE_FETCH_GUARD_ORIGINAL_CONSOLE_WARN__ = originalConsoleWarn

  const shouldSkipAbortLog = (args: any[]) => {
    const firstArg = String(args[0] || '')
    const hasAbortReason = args.some((arg: any) => {
      if (!arg) return false
      if (typeof arg === 'string') {
        return arg.includes('signal is aborted') || arg.includes('aborted')
      }
      if (typeof arg === 'object' && 'reason' in arg) {
        return isAbortError((arg as any).reason)
      }
      return isAbortError(arg)
    })

    if (firstArg.includes('Fetch error') && hasAbortReason) return true
    if (firstArg.includes('abort') && firstArg.includes('Fetch') && hasAbortReason) return true
    if (firstArg.toLowerCase().includes('aborterror') && hasAbortReason) return true

    return false
  }

  console.error = ((...args: any[]) => {
    if (shouldSkipAbortLog(args)) return
    originalConsoleError.apply(console, args)
  }) as any

  console.warn = ((...args: any[]) => {
    if (shouldSkipAbortLog(args)) return
    originalConsoleWarn.apply(console, args)
  }) as any
}

// Ensure the guard is installed as soon as this module is evaluated.
installFetchGuard()

export default function GlobalFetchGuard() {
  // Keep a tiny effect so the component isn't tree-shaken in dev builds.
  useEffect(() => {}, [])

  return null
}
